import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

version = {}
with open("./vortexasdk/version.py") as fp:
    exec(fp.read(), version)

setuptools.setup(
    name="vortexasdk",
    version=version["__version__"],
    author="Vortexa Developers",
    author_email="developers@vortexa.com",
    description="Vortexa SDK",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=setuptools.find_packages(),
    url="https://github.com/vortechsa/python-sdk",
    license="Apache License 2.0",
    classifiers=[
        "Programming Language :: Python :: 3.7",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
    install_requires=[
        "Jinja2==3.1.2",
        "Markdown==3.4.1",
        "MarkupSafe==2.1.1",
        "Send2Trash==1.8.0",
        "argon2-cffi==21.3.0",
        "argon2-cffi-bindings==21.2.0",
        "aspy.yaml==1.3.0",
        "atomicwrites==1.4.1",
        "attrs==22.1.0",
        "backcall==0.2.0",
        "beautifulsoup4==4.11.1",
        "bleach==5.0.1",
        "certifi==2022.6.15",
        "cffi==1.15.1",
        "cfgv==3.3.1",
        "charset-normalizer==2.0.12",
        "click==8.1.3",
        "cycler==0.11.0",
        "debugpy==1.6.2",
        "decorator==5.1.1",
        "defusedxml==0.7.1",
        "distlib==0.3.5",
        "entrypoints==0.3"
        "et-xmlfile==1.1.0",
        "fastjsonschema==2.16.1",
        "filelock==3.7.1",
        "flake8==3.7.9",
        "flatten-dict==0.2.0",
        "ghp-import==2.1.0",
        "identify==2.5.2",
        "idna==3.3",
        "importlib-metadata==4.12.0",
        "importlib-resources==5.9.0",
        "ipykernel==6.15.1",
        "ipython==7.34.0",
        "ipython-genutils==0.2.0",
        "ipywidgets==7.7.1",
        "jedi==0.18.1",
        "jsons==1.0.0",
        "jsonschema==4.9.0",
        "jupyter==1.0.0",
        "jupyter-client==7.3.4",
        "jupyter-console==6.4.4",
        "jupyter-core==4.11.1",
        "jupyterlab-pygments==0.2.2",
        "jupyterlab-widgets==1.1.1",
        "kiwisolver==1.4.4",
        "matplotlib==3.3.4",
        "matplotlib-inline==0.1.3",
        "mccabe==0.6.1",
        "mergedeep==1.3.4",
        "mistune==0.8.4",
        "mkdocs==1.2.4",
        "more-itertools==8.13.0",
        "mypy==0.770",
        "mypy-extensions==0.4.3",
        "nbclient==0.6.6",
        "nbconvert==6.5.0",
        "nbformat==5.4.0",
        "nest-asyncio==1.5.5",
        "nodeenv==1.7.0",
        "notebook==6.4.12",
        "numpy==1.21.6",
        "openpyxl==3.0.7",
        "packaging==21.3",
        "pandas==1.3.5",
        "pandocfilters==1.5.0",
        "parso==0.8.3",
        "pathlib2==2.3.7.post1",
        "patsy==0.5.2",
        "pexpect==4.8.0",
        "pickleshare==0.7.5",
        "pillow==9.2.0",
        "pkgutil-resolve-name==1.3.10",
        "platformdirs==2.5.2",
        "pluggy==0.13.1",
        "pre-commit==1.20.0",
        "prometheus-client==0.14.1",
        "prompt-toolkit==3.0.30",
        "psutil==5.9.1",
        "ptyprocess==0.7.0",
        "py==1.11.0",
        "pycodestyle==2.5.0",
        "pycparser==2.21",
        "pydoc-markdown==2.0.5",
        "pyflakes==2.1.1",
        "pygments==2.12.0",
        "pyparsing==3.0.9",
        "pyrsistent==0.18.1",
        "pytest==5.2.4",
        "python-dateutil==2.8.2",
        "pytz==2022.1",
        "pyyaml==5.4.1",
        "pyyaml-env-tag==0.1",
        "pyzmq==23.2.0",
        "qtconsole==5.3.1",
        "qtpy==2.1.0",
        "requests==2.27.1",
        "scipy==1.7.3",
        "six==1.12.0",
        "soupsieve==2.3.2.post1",
        "statsmodels==0.12.2",
        "tabulate==0.8.7",
        "terminado==0.15.0",
        "tinycss2==1.1.1",
        "toml==0.10.2",
        "tornado==6.2",
        "tqdm==4.38.0",
        "traitlets==5.3.0",
        "typed-ast==1.4.3",
        "typing-extensions==4.3.0",
        "typish==1.2.0",
        "urllib3==1.26.11",
        "virtualenv==20.16.2",
        "vortexasdk==0.37.1",
        "watchdog==2.1.9",
        "wcwidth==0.2.5",
        "webencodings==0.5.1",
        "widgetsnbextension==3.6.1",
        "xlrd==1.2.0",
        "zipp==3.8.1"
    ],
    extras_require={
        "tests": [
            "flake8==3.7.9",
            "mkdocs==1.2.4",
            "mypy==0.770",
            "pre-commit==1.20.0",
            "pytest==5.2.4",
            "pydoc-markdown==2.0.5",
            "pyyaml<6.0.0",
            "six==1.12.0",
            "tabulate==0.8.7",
            "xlrd==1.2.0",
            "openpyxl==3.0.7",
        ],
        "deploy": ["wheel==0.36.2", "twine==3.3.0"],
    },
)
