"""Vortexa Python SDK."""

# noinspection PyUnresolvedReferences
from vortexasdk.endpoints import (
    AssetTanks,
    Attributes,
    CanalTransit,
    CanalTransitTimeseries,
    CargoMovements,
    CargoTimeSeries,
    Corporations,
    Geographies,
    Products,
    Vessels,
    VesselAvailabilitySearch,
    VesselAvailabilityTimeseries,
    VesselAvailabilityBreakdown,
    Fixtures,
    EIAForecasts,
    OriginBreakdown,
    DestinationBreakdown,
    ProductBreakdown,
    ParentProductBreakdown,
    MovementStatusBreakdown,
    VesselClassBreakdown,
    StorageTerminals,
    OnshoreInventoriesTimeseries,
    OnshoreInventoriesSearch,
    FreightPricingSearch,
    FreightPricingTimeseries,
    VoyagesTimeseries,
    VoyagesTimeseriesV2,
    VoyagesGeographyBreakdown,
    VoyagesVesselClassBreakdown,
    VoyagesProductBreakdown,
    VoyagesRoutesBreakdown,
    VoyagesCongestionBreakdown,
    VoyagesTopHits,
    VoyagesSearchEnriched,
    VesselSummary,
    VesselPositions,
    Refineries,
    AnywhereFreightPricingLatestUpdateTimestamp,
    AnywhereFreightPricingPriceTimeseries,
    AnywhereFreightPricingGetPriceDetails,
    AnywhereFreightPricingPostPriceDetails,
    AnywhereFreightPricingTopPortsDestination,
    AnywhereFreightPricingTopPortsOrigin,
    AnywhereFreightPricingVesselClassesDetails,
    # AFP types
    AfpAvoidZone,
    AfpFrequency,
    AfpProduct,
    AfpRoute,
    AfpUnit,
    AfpVesselClass,
)

# noinspection PyUnresolvedReferences
from vortexasdk.version import __version__

# noinspection PyUnresolvedReferences
from vortexasdk.check_setup import run_all_checks

# Explicitly list all exported classes, to help MyPy know what is available
__all__ = [
    "AssetTanks",
    "Attributes",
    "CanalTransit",
    "CanalTransitTimeseries",
    "CargoMovements",
    "CargoTimeSeries",
    "Corporations",
    "Geographies",
    "Products",
    "Vessels",
    "VesselAvailabilitySearch",
    "VesselAvailabilityTimeseries",
    "VesselAvailabilityBreakdown",
    "Fixtures",
    "EIAForecasts",
    "OriginBreakdown",
    "DestinationBreakdown",
    "ProductBreakdown",
    "ParentProductBreakdown",
    "MovementStatusBreakdown",
    "VesselClassBreakdown",
    "StorageTerminals",
    "OnshoreInventoriesTimeseries",
    "OnshoreInventoriesSearch",
    "FreightPricingSearch",
    "FreightPricingTimeseries",
    "VoyagesTimeseries",
    "VoyagesTimeseriesV2",
    "VoyagesGeographyBreakdown",
    "VoyagesVesselClassBreakdown",
    "VoyagesProductBreakdown",
    "VoyagesRoutesBreakdown",
    "VoyagesCongestionBreakdown",
    "VoyagesTopHits",
    "VoyagesSearchEnriched",
    "VesselSummary",
    "VesselPositions",
    "Refineries",
    "AnywhereFreightPricingLatestUpdateTimestamp",
    "AnywhereFreightPricingPriceTimeseries",
    "AnywhereFreightPricingGetPriceDetails",
    "AnywhereFreightPricingPostPriceDetails",
    "AnywhereFreightPricingTopPortsDestination",
    "AnywhereFreightPricingTopPortsOrigin",
    "AnywhereFreightPricingVesselClassesDetails",
    # AFP types
    "AfpAvoidZone",
    "AfpFrequency",
    "AfpProduct",
    "AfpRoute",
    "AfpUnit",
    "AfpVesselClass",
    "__version__",
    "run_all_checks",
]
