"""Sample Columns:

cargo_movement_id
events.cargo_port_load_event.0.end_timestamp
events.cargo_port_load_event.0.event_type
events.cargo_port_load_event.0.location.country.id
events.cargo_port_load_event.0.location.country.label
events.cargo_port_load_event.0.location.country.layer
events.cargo_port_load_event.0.location.country.probability
events.cargo_port_load_event.0.location.country.source
events.cargo_port_load_event.0.location.port.id
events.cargo_port_load_event.0.location.port.label
events.cargo_port_load_event.0.location.port.layer
events.cargo_port_load_event.0.location.port.probability
events.cargo_port_load_event.0.location.port.source
events.cargo_port_load_event.0.location.region.id
events.cargo_port_load_event.0.location.region.label
events.cargo_port_load_event.0.location.region.layer
events.cargo_port_load_event.0.location.region.probability
events.cargo_port_load_event.0.location.region.source
events.cargo_port_load_event.0.location.shipping_region.id
events.cargo_port_load_event.0.location.shipping_region.label
events.cargo_port_load_event.0.location.shipping_region.layer
events.cargo_port_load_event.0.location.shipping_region.probability
events.cargo_port_load_event.0.location.shipping_region.source
events.cargo_port_load_event.0.location.terminal.id
events.cargo_port_load_event.0.location.terminal.label
events.cargo_port_load_event.0.location.terminal.layer
events.cargo_port_load_event.0.location.terminal.probability
events.cargo_port_load_event.0.location.terminal.source
events.cargo_port_load_event.0.location.trading_region.id
events.cargo_port_load_event.0.location.trading_region.label
events.cargo_port_load_event.0.location.trading_region.layer
events.cargo_port_load_event.0.location.trading_region.probability
events.cargo_port_load_event.0.location.trading_region.source
events.cargo_port_load_event.0.location.trading_subregion.id
events.cargo_port_load_event.0.location.trading_subregion.label
events.cargo_port_load_event.0.location.trading_subregion.layer
events.cargo_port_load_event.0.location.trading_subregion.probability
events.cargo_port_load_event.0.location.trading_subregion.source
events.cargo_port_load_event.0.pos.0
events.cargo_port_load_event.0.pos.1
events.cargo_port_load_event.0.probability
events.cargo_port_load_event.0.start_timestamp
events.cargo_port_load_event.0.vessel_id
events.cargo_port_unload_event.0.end_timestamp
events.cargo_port_unload_event.0.event_type
events.cargo_port_unload_event.0.location.country.id
events.cargo_port_unload_event.0.location.country.label
events.cargo_port_unload_event.0.location.country.layer
events.cargo_port_unload_event.0.location.country.probability
events.cargo_port_unload_event.0.location.country.source
events.cargo_port_unload_event.0.location.port.id
events.cargo_port_unload_event.0.location.port.label
events.cargo_port_unload_event.0.location.port.layer
events.cargo_port_unload_event.0.location.port.probability
events.cargo_port_unload_event.0.location.port.source
events.cargo_port_unload_event.0.location.region.id
events.cargo_port_unload_event.0.location.region.label
events.cargo_port_unload_event.0.location.region.layer
events.cargo_port_unload_event.0.location.region.probability
events.cargo_port_unload_event.0.location.region.source
events.cargo_port_unload_event.0.location.shipping_region.id
events.cargo_port_unload_event.0.location.shipping_region.label
events.cargo_port_unload_event.0.location.shipping_region.layer
events.cargo_port_unload_event.0.location.shipping_region.probability
events.cargo_port_unload_event.0.location.shipping_region.source
events.cargo_port_unload_event.0.location.terminal.id
events.cargo_port_unload_event.0.location.terminal.label
events.cargo_port_unload_event.0.location.terminal.layer
events.cargo_port_unload_event.0.location.terminal.probability
events.cargo_port_unload_event.0.location.terminal.source
events.cargo_port_unload_event.0.location.trading_block.id
events.cargo_port_unload_event.0.location.trading_block.label
events.cargo_port_unload_event.0.location.trading_block.layer
events.cargo_port_unload_event.0.location.trading_block.probability
events.cargo_port_unload_event.0.location.trading_block.source
events.cargo_port_unload_event.0.location.trading_region.id
events.cargo_port_unload_event.0.location.trading_region.label
events.cargo_port_unload_event.0.location.trading_region.layer
events.cargo_port_unload_event.0.location.trading_region.probability
events.cargo_port_unload_event.0.location.trading_region.source
events.cargo_port_unload_event.0.location.trading_subregion.id
events.cargo_port_unload_event.0.location.trading_subregion.label
events.cargo_port_unload_event.0.location.trading_subregion.layer
events.cargo_port_unload_event.0.location.trading_subregion.probability
events.cargo_port_unload_event.0.location.trading_subregion.source
events.cargo_port_unload_event.0.pos.0
events.cargo_port_unload_event.0.pos.1
events.cargo_port_unload_event.0.probability
events.cargo_port_unload_event.0.start_timestamp
events.cargo_port_unload_event.0.vessel_id
product.grade.id
product.grade.label
product.grade.layer
product.grade.probability
product.grade.source
product.group.id
product.group.label
product.group.layer
product.group.probability
product.group.source
product.group_product.id
product.group_product.label
product.group_product.layer
product.group_product.probability
product.group_product.source
quantity
status
vessels.0.corporate_entities.charterer.id
vessels.0.corporate_entities.charterer.label
vessels.0.corporate_entities.charterer.layer
vessels.0.corporate_entities.charterer.probability
vessels.0.corporate_entities.charterer.source
vessels.0.corporate_entities.commercial_owner.id
vessels.0.corporate_entities.commercial_owner.label
vessels.0.corporate_entities.commercial_owner.layer
vessels.0.corporate_entities.commercial_owner.probability
vessels.0.corporate_entities.commercial_owner.source
vessels.0.corporate_entities.time_charterer.end_timestamp
vessels.0.corporate_entities.time_charterer.id
vessels.0.corporate_entities.time_charterer.label
vessels.0.corporate_entities.time_charterer.layer
vessels.0.corporate_entities.time_charterer.probability
vessels.0.corporate_entities.time_charterer.source
vessels.0.corporate_entities.time_charterer.start_timestamp
vessels.0.cubic_capacity
vessels.0.dwt
vessels.0.end_timestamp
vessels.0.fixture_fulfilled
vessels.0.fixture_id
vessels.0.id
vessels.0.imo
vessels.0.mmsi
vessels.0.name
vessels.0.start_timestamp
vessels.0.status
vessels.0.vessel_class
vessels.0.voyage_id
vessels.1.corporate_entities.charterer.id
vessels.1.corporate_entities.charterer.label
vessels.1.corporate_entities.charterer.layer
vessels.1.corporate_entities.charterer.probability
vessels.1.corporate_entities.charterer.source
vessels.1.corporate_entities.commercial_owner.id
vessels.1.corporate_entities.commercial_owner.label
vessels.1.corporate_entities.commercial_owner.layer
vessels.1.corporate_entities.commercial_owner.probability
vessels.1.corporate_entities.commercial_owner.source
vessels.1.cubic_capacity
vessels.1.dwt
vessels.1.end_timestamp
vessels.1.fixture_fulfilled
vessels.1.fixture_id
vessels.1.id
vessels.1.imo
vessels.1.mmsi
vessels.1.name
vessels.1.start_timestamp
vessels.1.status
vessels.1.tags.0.end_timestamp
vessels.1.tags.0.start_timestamp
vessels.1.tags.0.tag
vessels.1.vessel_class
vessels.1.voyage_id
vessels.2.corporate_entities.charterer.id
vessels.2.corporate_entities.charterer.label
vessels.2.corporate_entities.charterer.layer
vessels.2.corporate_entities.charterer.probability
vessels.2.corporate_entities.charterer.source
vessels.2.corporate_entities.commercial_owner.id
vessels.2.corporate_entities.commercial_owner.label
vessels.2.corporate_entities.commercial_owner.layer
vessels.2.corporate_entities.commercial_owner.probability
vessels.2.corporate_entities.commercial_owner.source
vessels.2.cubic_capacity
vessels.2.dwt
vessels.2.end_timestamp
vessels.2.fixture_fulfilled
vessels.2.fixture_id
vessels.2.id
vessels.2.imo
vessels.2.mmsi
vessels.2.name
vessels.2.start_timestamp
vessels.2.status
vessels.2.vessel_class
vessels.2.voyage_id

"""
